version: '3'

services:
  ##
  # Application container
  #
  app:
    image: openwebslides/openwebslides:latest
    env_file:
      - openwebslides.env
    environment:
      - RAILS_ENV=production
      - NODE_ENV=production
    volumes:
      - public:/app/public/
      - data:/app/data/
      - uploads:/app/tmp/uploads/
    depends_on:
      - postgres
      - sidekiq
      - redis
    links:
      - postgres
      - redis

  ##
  # Database container
  #
  postgres:
    image: postgres:9.6
    volumes:
      - postgres:/var/lib/postgresql/data/
    restart: always

  ##
  # Sidekiq container
  #
  sidekiq:
    image: openwebslides/openwebslides:latest
    env_file:
      - openwebslides.env
    volumes:
      - /var/run/postgresql/:/var/run/postgresql/
      - uploads:/app/tmp/uploads/
    depends_on:
      - postgres
      - redis
    links:
      - redis
    command: bundle exec sidekiq
    restart: always

  ##
  # Redis container
  #
  redis:
    image: redis:3.0
    volumes:
      - redis:/var/lib/redis/data/
    restart: always

  ##
  # Web server container
  #
  nginx:
    image: nginx:1.13
    volumes:
      - public:/app/public/
      - ${PWD}/nginx.conf:/etc/nginx/nginx.conf
      - ${PWD}/nginx-proxy.conf:/etc/nginx/nginx-proxy.conf
      - uploads:/app/tmp/uploads/
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
    depends_on:
      - app
    links:
      - app
    restart: always

volumes:
  # Repository data volume
  data:

  # Public assets (frontend) volume
  public:

  # Temporary uploaded data
  uploads:

  # Database volume
  postgres:

  # Redis volume
  redis:

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 192.168.8.1/24

